var sourceData = [{
	'img': '../images/persional.jpg',
	'rewardTitle': '转发朋友圈第二条',
	'rewardMoney': 33,
	'rewarded': 0,
	'rewardSx': 20,
	'type': 1
}, {
	'img': '../images/g1.jpg',
	'rewardTitle': '集关注',
	'rewardMoney': 72,
	'rewarded': 5,
	'rewardSx': 10,
	'type': 2
}, {
	'img': '../images/d2.png',
	'rewardTitle': '网站用户注册',
	'rewardMoney': 510,
	'rewarded': 1,
	'rewardSx': 7,
	'type': 3
}, {
	'img': '../images/persional.jpg',
	'rewardTitle': '转发朋友圈第一条',
	'rewardMoney': 22,
	'rewarded': 0,
	'rewardSx': 20,
	'type': 1
}, {
	'img': '../images/g1.jpg',
	'rewardTitle': '集关注',
	'rewardMoney': 81,
	'rewarded': 5,
	'rewardSx': 10,
	'type': 2
}, {
	'img': '../images/d2.png',
	'rewardTitle': '网站用户注册',
	'rewardMoney': 320,
	'rewarded': 1,
	'rewardSx': 7,
	'type': 3
}, {
	'img': '../images/persional.jpg',
	'rewardTitle': '转发朋友圈第三条',
	'rewardMoney': 68,
	'rewarded': 0,
	'rewardSx': 20,
	'type': 1
}, {
	'img': '../images/g1.jpg',
	'rewardTitle': '集关注',
	'rewardMoney': 91,
	'rewarded': 5,
	'rewardSx': 10,
	'type': 2
}, {
	'img': '../images/d2.png',
	'rewardTitle': '网站用户注册',
	'rewardMoney': 8,
	'rewarded': 1,
	'rewardSx': 7,
	'type': 3
}];